# Generated by Django 4.2.5 on 2023-09-26 12:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 9, 26, 12, 34, 26, 748075, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('w_date', models.DateField(verbose_name='date')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weights.person')),
            ],
        ),
    ]
