# Generated by Django 4.2.5 on 2023-09-30 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 30, 9, 53, 20, 236473, tzinfo=datetime.timezone.utc)),
        ),
    ]
